### ISSUE TITLE
Showcase our meetup's replays

### ISSUE THREAD

**Issue by aloisdg** [d-edge/JoinUs#2]
Hello,

Since we publish most our meetup on [our YouTube channel](https://www.youtube.com/watch?v=lcuTJYw-jsw&list=PLychnrjxWBViBfk5V68i6tVZDM5UhNhBB), we would like to showcase them on this repository.

- Create a MEETUP.md file
- Fill it with the name and a youtube link of each replay
- Add a youtube thumbnail to each replay

```
# Meetup

## meetup.title

[![thumbnail](meetup.imagelink)](meetup.youtubelink)

meetup.description

## meetup2.title

[![thumbnail](meetup2.imagelink)](meetup2.youtubelink)

meetup2.description
```

A whole new issue could be to move from Picture to Gif (say jif). The idea would be to eplace the youtube thumbnail by a gif of each thumbnail or by a gif of a section of the video". We will see later on.

If we could automate the process with an Azure function, a GitHub action or even a Zapier recipe, it would be awesome.

Talked with @ytyukhnin

**Comment by shreyadenny** [comment]
Hey @aloisdg may I work on this issue?
